version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wallet
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/wallet?schema=public
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: sh -c "pnpm prisma:deploy && pnpm start:prod" 


volumes:
  postgres-data: